version: "3.3"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - "9000"
    ports:
      - "9000:9000"
    links:
      - mysql:mysql
    depends_on:
      - mysql
    volumes:
       - ./source:/var/www/html:z
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8081:80"
    links:
      - php:php
    volumes:
      - ./nginx/web.conf:/etc/nginx/conf.d/default.conf
      - ./source:/var/www/html:z
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
      - ./source/db/default-db.sql:/docker-entrypoint-initdb.d/homestead.sql
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - docker-net
  # jenkins:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-jenkins
  #   container_name: jenkins
  #   restart: always
  #   user: root
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./jenkins_home:/var/jenkins_home
